### ISSUE TITLE
Outdated projects

### ISSUE THREAD

**Issue by RafaelLinux** [forart/HyMPS#31]
I don't really know the purpose of this list, but after what I've said, it seems to me more like a "history" of applications than a reference page to go to when looking for multimedia software.

EDIT: sorry, accidentally edited your original message.

**Comment by forart** [comment]
Hi there, thanks for visiting our pages !

>I don't really know the purpose of this list, but after what I've said, it seems to me more like a "history" of applications than a reference page to go to when looking for multimedia software.
>
The HyMPS' collection is geared towards open source a/v developers: we're trying to promote collaborations/knowledge exchange for the mutual evolution of their softwares (this is the reason of the sorting order, for example).
That's why we also decided to consider obsolete projects (which can serve as inspiration for new features of others) as long as they have sources available in their repositories.

In any case, feel free to share resources you know or join [our discussions](https://github.com/forart/HyMPS/discussions) to promote alternative approaches.

Thanks in advance.

HyMPS "resources" collection is developers-oriented: we're trying to push collaborations/knowledge exchange for mutual evolution of open source a/v projects (that's the reason of the projects sorting).
We decided to share outdated projects too (which can serve as inspiration for new features from others) as long as they have sources available in their repos.

Feel free to share resources you know or join [our discussions](https://github.com/forart/HyMPS/discussions) to promote alternative approaches, anyway.

Thanks in advance.

**Comment by RafaelLinux** [comment]
Thank you very much for the clarification. I had misunderstood that your compilation was aimed at end users, hence my message. In fact, among the projects there is an Olive "Fork" with QT, and I quickly went to see it, but I found out that it was abandoned more than 4 years ago and the disappointment of discovering it led me to not understand what was the point of putting this application in your list.

For the moment I have a suggestion regarding accessibility: The colour scheme chosen for the "last commit" column makes it very difficult to read. I guess you can change it to another colour scheme without much difficulty, please do so.

As a suggestion - although I'm not sure what kind of licence it has - I use Ocenaudio (https://www.ocenaudio.com/whatis) to edit audio files. It is fast and cross-platform, but there is no mention of a licence.

**Comment by forart** [comment]
> In fact, among the projects there is an Olive "Fork" with QT, and I quickly went to see it, but I found out that it was abandoned more than 4 years ago and the disappointment of discovering it led me to not understand what was the point of putting this application in your list.
>

You're right, @orange4glace hasn't updated [Nlive](https://github.com/orange4glace/nlive) for a long time but he hasn't archived the project yet: maybe he needs some encouragement (or help) ?
Why don't you try - as we did in [this issue on his repo](https://github.com/orange4glace/nlive/issues/3) - to stimulate other active developers with whom he could perhaps collaborate to carry the project forward?
(that's the spirit of HyMPS)


> For the moment I have a suggestion regarding accessibility: The colour scheme chosen for the "last commit" column makes it very difficult to read. I guess you can change it to another colour scheme without much difficulty, please do so.
>

Sorry but, as we use [badgen](https://badgen.net/) and [Shields.io](https://shields.io/) services to generate the badges, their colors are predefined.
Anyway, again, you can open an issue in their respective repos:
- https://github.com/badgen/badgen.net
- https://github.com/badges/shields


> As a suggestion - although I'm not sure what kind of licence it has - I use Ocenaudio (https://www.ocenaudio.com/whatis) to edit audio files. It is fast and cross-platform, but there is no mention of a licence.
>
We of course have already "encountered" @guidefloripa's Ocenaudio in the past but, since its source code don't seem to be available at the moment, it does not fit our requirements to be listed.

Thanks again for your feedbacks !

**Comment by guidefloripa** [comment]
> We of course have already "encountered" @guidefloripa's Ocenaudio in the past but, since its source code don't seem to be available at the moment, it does not fit our requirements to be listed.

I worked for many years on the Ocenaudio's project. Ocenaudio is a free-to-use software, but for more information I suggest you contact directly the project: https://www.ocenaudio.com/feedback

**Comment by RafaelLinux** [comment]
> > We of course have already "encountered" @guidefloripa's Ocenaudio in the past but, since its source code don't seem to be available at the moment, it does not fit our requirements to be listed.
> 
> I worked for many years on the Ocenaudio's project. Ocenaudio is a free-to-use software, but for more information I suggest you contact directly the project: https://www.ocenaudio.com/feedback

Although I don't know if you are commenting for me, I do have something to say about the "feedback" with Ocenaudio. I have sent them messages on three occasions for different reasons. Either for improvements, bugs or suggesting to update the page (in the download section, they refer to openSUSE 42.3 .... which is a version that disappeared 5 years ago). On none of the occasions they have replied to me, even though I have written to them politely and thankfully, so I doubt very much that they will reply to anyone.
Nor is it understandable why there is no "Licensing" section on the website.
